name: "Chrony"
version: "0.1.0"
slug: "chrony"
description: "Chrony time synchronization service"
url: "https://github.com/bborchers/ha-addons-chrony/tree/main/chrony"
image: "ghcr.io/bborchers/ha-addons-chrony/{arch}"
arch:
  - aarch64
  - amd64
privileged:
  - SYS_TIME
init: false
options:
  servers:
    - pool.ntp.org
  nts: false
schema:
  servers: list
  nts: bool
